import type { SeedIndustryDataset } from '../industry.types.js';

export const AUTOMOTIVE_DATASET: SeedIndustryDataset = {
  id: 'automotive',
  name: 'Otomotif & Komponen Presisi',
  code: 'IND-AUTO',
  description: 'Komponen presisi otomotif: Stamping, CNC Machining, Sub-assembly, dan Quality Gate.',
  companyName: 'PT Cikarang Autoparts Presisi',
  warehouses: [
    { code: 'WH-RM-01', name: 'Gudang Bahan Baku & Coil', type: 'RAW_MATERIAL' },
    { code: 'WH-FG-01', name: 'Gudang Finished Goods Otomotif', type: 'FINISHED_GOODS' },
  ],
  workCenters: [
    { code: 'WC-STAMP', name: 'Work Center Stamping', capacityPerShift: 1200 },
    { code: 'WC-CNC', name: 'Work Center CNC Machining', capacityPerShift: 800 },
    { code: 'WC-ASSY', name: 'Work Center Sub-Assembly', capacityPerShift: 600 },
    { code: 'WC-QC', name: 'Work Center Final QC & Testing', capacityPerShift: 1500 },
  ],
  processes: [
    { code: 'PROC-STAMP', name: 'Stamping & Pressing', sequenceDefault: 1 },
    { code: 'PROC-CNC', name: 'Precision CNC Machining', sequenceDefault: 2 },
    { code: 'PROC-HEAT', name: 'Heat Treatment & Coating', sequenceDefault: 3 },
    { code: 'PROC-ASSY', name: 'Sub-Assembly & Torque Check', sequenceDefault: 4 },
    { code: 'PROC-QC', name: 'Final Quality Gate Inspection', sequenceDefault: 5 },
  ],
  machines: [
    { code: 'PRESS-250T', name: 'Hydraulic Press 250 Ton', idealCycleTimeSeconds: 8, workCenterCode: 'WC-STAMP' },
    { code: 'CNC-LATHE-01', name: 'CNC Turning Lathe Brother', idealCycleTimeSeconds: 24, workCenterCode: 'WC-CNC' },
    { code: 'CNC-MILL-02', name: '5-Axis CNC Milling Mazak', idealCycleTimeSeconds: 45, workCenterCode: 'WC-CNC' },
    { code: 'ROBOT-WELD-01', name: 'Yaskawa Robotic Welding Station', idealCycleTimeSeconds: 18, workCenterCode: 'WC-ASSY' },
    { code: 'CMM-INSPECT', name: 'Mitutoyo Coordinate Measuring Machine', idealCycleTimeSeconds: 15, workCenterCode: 'WC-QC' },
  ],
  lines: [
    { code: 'LINE-AUTO-A', name: 'Lini Produksi Komponen Rem Alpha' },
    { code: 'LINE-AUTO-B', name: 'Lini Sub-Assembly Powertrain Beta' },
  ],
  shifts: [
    { name: 'Shift Pagi', startTime: '07:00', endTime: '15:00', breakMinutes: 60 },
    { name: 'Shift Sore', startTime: '15:00', endTime: '23:00', breakMinutes: 60 },
    { name: 'Shift Malam', startTime: '23:00', endTime: '07:00', breakMinutes: 60 },
  ],
  parts: [
    { sku: 'RM-STL-ROD', name: 'Alloy Steel Bar Rod 45C (Dia 60mm)', unit: 'KG', category: 'RAW_MATERIAL', initialStock: 8500 },
    { sku: 'RM-CAST-DISC', name: 'Grey Cast Iron Blank Disc FG25', unit: 'PCS', category: 'RAW_MATERIAL', initialStock: 2400 },
    { sku: 'RM-FRIC-MAT', name: 'Ceramic Friction Material Block', unit: 'KG', category: 'RAW_MATERIAL', initialStock: 1200 },
    { sku: 'RM-ALUM-6061', name: 'Aluminum Billet 6061-T6', unit: 'KG', category: 'RAW_MATERIAL', initialStock: 3500 },
    { sku: 'COMP-PIN-01', name: 'Guide Caliper Pin Hardened', unit: 'PCS', category: 'COMPONENT', initialStock: 6000 },
    { sku: 'COMP-BOLT-M12', name: 'High-Tensile Bolt M12x1.5 Grade 10.9', unit: 'PCS', category: 'COMPONENT', initialStock: 15000 },
    { sku: 'COMP-RUB-SEAL', name: 'EPDM Piston Dust Boot & Seal', unit: 'SET', category: 'COMPONENT', initialStock: 4800 },
    { sku: 'PKG-VCI-BOX', name: 'Corrugated Carton with VCI Anti-Rust Film', unit: 'BOX', category: 'PACKAGING', initialStock: 3000 },
  ],
  products: [
    { sku: 'PRD-DISC-01', name: 'Ventilated Brake Disc Front (280mm)', unit: 'PCS', idealCycleTimeSeconds: 28, category: 'Braking System' },
    { sku: 'PRD-PAD-02', name: 'Ceramic Brake Pad Set Low-Metallic', unit: 'SET', idealCycleTimeSeconds: 16, category: 'Braking System' },
    { sku: 'PRD-MNT-03', name: 'Engine Bracket Mount Front LH', unit: 'PCS', idealCycleTimeSeconds: 35, category: 'Powertrain' },
    { sku: 'PRD-SUSP-04', name: 'Suspension Lower Arm Bracket', unit: 'PCS', idealCycleTimeSeconds: 22, category: 'Chassis' },
    { sku: 'PRD-STR-05', name: 'Steering Knuckle Housing RH', unit: 'PCS', idealCycleTimeSeconds: 42, category: 'Steering' },
  ],
  boms: [
    {
      bomNumber: 'BOM-AUTO-001',
      productSku: 'PRD-DISC-01',
      bomName: 'BOM Ventilated Brake Disc Standard',
      version: 'v1.0',
      status: 'ACTIVE',
      effectiveDate: '2026-01-01',
      description: 'Struktur material piringan rem berventilasi presisi dengan anti-karat VCI packaging.',
      items: [
        { componentPartSku: 'RM-CAST-DISC', componentType: 'RAW_MATERIAL', quantity: 1, uom: 'PCS', scrapPercentage: 1.5, sequence: 1 },
        { componentPartSku: 'PKG-VCI-BOX', componentType: 'PACKAGING', quantity: 1, uom: 'BOX', sequence: 2 },
      ],
    },
    {
      bomNumber: 'BOM-AUTO-002',
      productSku: 'PRD-PAD-02',
      bomName: 'BOM Ceramic Brake Pad Set OEM',
      version: 'v1.0',
      status: 'ACTIVE',
      effectiveDate: '2026-01-01',
      description: 'Pad rem keramik lengkap dengan shim dan guide pin kit.',
      items: [
        { componentPartSku: 'RM-FRIC-MAT', componentType: 'RAW_MATERIAL', quantity: 0.45, uom: 'KG', scrapPercentage: 2.0, sequence: 1 },
        { componentPartSku: 'COMP-PIN-01', componentType: 'COMPONENT', quantity: 2, uom: 'PCS', sequence: 2 },
        { componentPartSku: 'COMP-BOLT-M12', componentType: 'COMPONENT', quantity: 2, uom: 'PCS', sequence: 3 },
        { componentPartSku: 'PKG-VCI-BOX', componentType: 'PACKAGING', quantity: 1, uom: 'BOX', sequence: 4 },
      ],
    },
    {
      bomNumber: 'BOM-AUTO-003',
      productSku: 'PRD-MNT-03',
      bomName: 'BOM Engine Mount Bracket Assembly',
      version: 'v1.0',
      status: 'ACTIVE',
      effectiveDate: '2026-01-01',
      description: 'Bracket dudukan mesin dengan bushing peredam getaran.',
      items: [
        { componentPartSku: 'RM-ALUM-6061', componentType: 'RAW_MATERIAL', quantity: 1.85, uom: 'KG', scrapPercentage: 3.0, sequence: 1 },
        { componentPartSku: 'COMP-RUB-SEAL', componentType: 'COMPONENT', quantity: 1, uom: 'SET', sequence: 2 },
        { componentPartSku: 'COMP-BOLT-M12', componentType: 'COMPONENT', quantity: 4, uom: 'PCS', sequence: 3 },
      ],
    },
  ],
  customers: [
    { code: 'CUST-ASTRA', name: 'PT Astra Daihatsu Motor', email: 'procurement@daihatsu.astra.co.id', phone: '+62-21-6510001', address: 'Kawasan Industri KIIC Karawang' },
    { code: 'CUST-TOYOTA', name: 'PT Toyota Motor Manufacturing Indonesia', email: 'purchasing@toyota.co.id', phone: '+62-21-8980001', address: 'Kawasan Industri MM2100 Cikarang' },
    { code: 'CUST-HONDA', name: 'PT Honda Prospect Motor', email: 'supply_chain@hpm.co.id', phone: '+62-21-2990001', address: 'Kawasan Industri Mitrakarawang' },
    { code: 'CUST-SUZUKI', name: 'PT Suzuki Indomobil Motor', email: 'orders@suzuki.co.id', phone: '+62-21-8970001', address: 'Kawasan GIIC Cikarang' },
    { code: 'CUST-MITSUBISHI', name: 'PT Mitsubishi Motors Krama Yudha', email: 'vendor@mmki.co.id', phone: '+62-21-8960001', address: 'GIIC Deltamas Cikarang' },
  ],
  suppliers: [
    { code: 'SUP-KRAKATAU', name: 'PT Krakatau Posco', category: 'Steel & Raw Metals', contact: 'sales@krakatauposco.co.id' },
    { code: 'SUP-INDAH-ALUM', name: 'PT Indah Kiat Aluminum', category: 'Extrusion & Billets', contact: 'supply@indahalum.co.id' },
    { code: 'SUP-TOYODA-GOS', name: 'Toyoda Gosei Indonesia', category: 'Rubber Seals & Mounts', contact: 'sales@toyoda-gosei.co.id' },
    { code: 'SUP-FASTEN-IND', name: 'PT Indo Fasteners Mega', category: 'Industrial Bolts & Fasteners', contact: 'orders@indofastener.co.id' },
    { code: 'SUP-KARYA-BOX', name: 'PT Karya Box Packaging', category: 'Cartons & Anti-Rust VCI', contact: 'pack@karyabox.co.id' },
  ],
  routings: [
    { productSku: 'PRD-DISC-01', processCode: 'PROC-CNC', sequence: 1, workCenterCode: 'WC-CNC', machineCode: 'CNC-LATHE-01', standardCycleTimeSeconds: 28 },
    { productSku: 'PRD-DISC-01', processCode: 'PROC-QC', sequence: 2, workCenterCode: 'WC-QC', machineCode: 'CMM-INSPECT', standardCycleTimeSeconds: 15 },
    { productSku: 'PRD-PAD-02', processCode: 'PROC-STAMP', sequence: 1, workCenterCode: 'WC-STAMP', machineCode: 'PRESS-250T', standardCycleTimeSeconds: 8 },
    { productSku: 'PRD-PAD-02', processCode: 'PROC-ASSY', sequence: 2, workCenterCode: 'WC-ASSY', machineCode: 'ROBOT-WELD-01', standardCycleTimeSeconds: 18 },
    { productSku: 'PRD-PAD-02', processCode: 'PROC-QC', sequence: 3, workCenterCode: 'WC-QC', machineCode: 'CMM-INSPECT', standardCycleTimeSeconds: 12 },
  ],
  orders: [
    { orderNumber: 'PO-ASTRA-2026-001', customerCode: 'CUST-ASTRA', productSku: 'PRD-DISC-01', quantity: 2000, unit: 'PCS', targetDays: 5 },
    { orderNumber: 'PO-TOYOTA-2026-002', customerCode: 'CUST-TOYOTA', productSku: 'PRD-PAD-02', quantity: 3500, unit: 'SET', targetDays: 7 },
    { orderNumber: 'PO-HONDA-2026-003', customerCode: 'CUST-HONDA', productSku: 'PRD-MNT-03', quantity: 1200, unit: 'PCS', targetDays: 4 },
  ],
  workOrders: [
    { woNumber: 'WO-AUTO-2026-001', orderNumber: 'PO-ASTRA-2026-001', productSku: 'PRD-DISC-01', lineCode: 'LINE-AUTO-A', machineCode: 'CNC-LATHE-01', targetQuantity: 500, unit: 'PCS', status: 'IN_PROGRESS' },
    { woNumber: 'WO-AUTO-2026-002', orderNumber: 'PO-TOYOTA-2026-002', productSku: 'PRD-PAD-02', lineCode: 'LINE-AUTO-B', machineCode: 'PRESS-250T', targetQuantity: 800, unit: 'SET', status: 'RELEASED' },
  ],
  downtimeReasons: [
    { code: 'DT-TOOL-WEAR', name: 'Penggantian Cutting Tool Aus', category: 'TOOLING', isPlanned: false },
    { code: 'DT-DIE-JAM', name: 'Dies Macet / Jamming Stamping', category: 'MECHANICAL', isPlanned: false },
    { code: 'DT-PM-DAILY', name: 'Pembersihan & Pelumasan Harian', category: 'MAINTENANCE', isPlanned: true },
    { code: 'DT-MATERIAL-WAIT', name: 'Menunggu Pasokan Blank Disc', category: 'MATERIAL', isPlanned: false },
  ],
  rejectReasons: [
    { code: 'REJ-DIM-OFF', name: 'Dimensi Out of Spec (+/- 0.02mm)', category: 'DIMENSION' },
    { code: 'REJ-BURR-EXCESS', name: 'Geram Tajam Berlebih (Burr)', category: 'WORKMANSHIP' },
    { code: 'REJ-CRACK-SURF', name: 'Retak Rambut Mikro Permukaan', category: 'MATERIAL_DEFECT' },
  ],
};
